version: '3.9'

services:
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - server

  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    restart: always

